// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaldoDetailServiceClient is the client API for SaldoDetailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaldoDetailServiceClient interface {
	SaldoDetail(ctx context.Context, in *SaldoDetailRequest, opts ...grpc.CallOption) (*SaldoDetailResponse, error)
}

type saldoDetailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaldoDetailServiceClient(cc grpc.ClientConnInterface) SaldoDetailServiceClient {
	return &saldoDetailServiceClient{cc}
}

func (c *saldoDetailServiceClient) SaldoDetail(ctx context.Context, in *SaldoDetailRequest, opts ...grpc.CallOption) (*SaldoDetailResponse, error) {
	out := new(SaldoDetailResponse)
	err := c.cc.Invoke(ctx, "/proto.SaldoDetailService/SaldoDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaldoDetailServiceServer is the server API for SaldoDetailService service.
// All implementations must embed UnimplementedSaldoDetailServiceServer
// for forward compatibility
type SaldoDetailServiceServer interface {
	SaldoDetail(context.Context, *SaldoDetailRequest) (*SaldoDetailResponse, error)
	mustEmbedUnimplementedSaldoDetailServiceServer()
}

// UnimplementedSaldoDetailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSaldoDetailServiceServer struct {
}

func (UnimplementedSaldoDetailServiceServer) SaldoDetail(context.Context, *SaldoDetailRequest) (*SaldoDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaldoDetail not implemented")
}
func (UnimplementedSaldoDetailServiceServer) mustEmbedUnimplementedSaldoDetailServiceServer() {}

// UnsafeSaldoDetailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaldoDetailServiceServer will
// result in compilation errors.
type UnsafeSaldoDetailServiceServer interface {
	mustEmbedUnimplementedSaldoDetailServiceServer()
}

func RegisterSaldoDetailServiceServer(s grpc.ServiceRegistrar, srv SaldoDetailServiceServer) {
	s.RegisterService(&SaldoDetailService_ServiceDesc, srv)
}

func _SaldoDetailService_SaldoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaldoDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaldoDetailServiceServer).SaldoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SaldoDetailService/SaldoDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaldoDetailServiceServer).SaldoDetail(ctx, req.(*SaldoDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaldoDetailService_ServiceDesc is the grpc.ServiceDesc for SaldoDetailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaldoDetailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SaldoDetailService",
	HandlerType: (*SaldoDetailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaldoDetail",
			Handler:    _SaldoDetailService_SaldoDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/saldo-detail.proto",
}
